return {
    Ataques = {
		Hit1 = { Id = "rbxassetid://78388402434294", Fade = 0.1, Priority = Enum.AnimationPriority.Action, Speed = 1 },
		Hit2 = { Id = "rbxassetid://90205895048056", Fade = 0.1, Priority = Enum.AnimationPriority.Action, Speed = 1 },
		Hit3 = { Id = "rbxassetid://133327123232834", Fade = 0.1, Priority = Enum.AnimationPriority.Action, Speed = 1 },
		Hit4 = { Id = "rbxassetid://120354171805652", Fade = 0.1, Priority = Enum.AnimationPriority.Action, Speed = 1 },
		Hit5 = { Id = "rbxassetid://131596907935975", Fade = 0.1, Priority = Enum.AnimationPriority.Action, Speed = 1.5 },
    },
    Estados = {
		Stunned = { Id = "rbxassetid://123030830919911", Fade = 0.1, Priority = Enum.AnimationPriority.Action4, Looped = true, Speed = 0.5 },
		Block = { Id = "rbxassetid://106678915501594", Fade = 0.2, Priority = Enum.AnimationPriority.Action4, Looped = true, Speed = 0.5 },
		Dash1 = { Id = "rbxassetid://120848990643547", Fade = 0.2, Priority = Enum.AnimationPriority.Action4, Looped = true, Speed = 0.8 },
		Dash2 = { Id = "rbxassetid://80323131269526", Fade = 0.1, Priority = Enum.AnimationPriority.Action4, Looped = false, Speed = 1.5 },
    }
}